Project MPC {
  database_type: 'MSSQL'
  Note: '''
    # MPC Database
    **markdown content here**
  '''
}

Table Countries {
    Id int [pk, increment]
    Code varchar [note: "FR"]
}

Table Holdings {
    Id int [pk, increment]
    Code varchar [note: "SAPTEN"]
    Description varchar
}

Table Companies {
    Id int [pk, increment]
    Code varchar [note: "TEFR"]
    CountryId int [ref: > Countries.Id]
    HoldingGroupId int [ref: > HoldingGroups.Id]
}

Table Centers {
    Id int [pk, increment]
    Code varchar [note: "X200"]
    CompanyId int [ref: > Companies.Id]
    Description varchar [note: "SEAMLESS PIPE INDONESIA JAYA"]
}

Table HoldingGroups {
    Id int [pk, increment]
    HoldingId int [ref: > Holdings.Id]
    Description varchar [note: "Tenaris"]
}

Table MaterialGroupClients {
    Id int [pk, increment]
    Code varchar [note: "HW"]
}

Table MaterialGroupExiros {
    Id int [pk, increment]
    Code varchar [note: "HW"]
}

Table MaterialGroups {
    Id int [pk, increment]
    MaterialGroupClientId int [ref: > MaterialGroupClients.Id]
    MaterialGroupExirosId int [ref: > MaterialGroupExiros.Id]
}

Table MaterialGroupCultures {
    MaterialGroupId int [ref: > MaterialGroups.Id]
    CultureId int [ref: > Cultures.Id]
    Description varchar [note: "Hardware"]
    Indexes {
        (MaterialGroupId, CultureId)
    }
}

Table MaterialTypes {
    Id int [pk, increment]
    Code varchar [note: "PC"]
}

Table SapMaterials {
    Id int [pk, increment]
    Code varchar [note: "40041990"]
}

Table MaterialCodifieds{
    Id int [pk, increment]
    MaterialId int [ref: > Materials.Id]
    SapMaterialId int [ref: > SapMaterials.Id]
    MaterialTypeId int [ref: > MaterialTypes.Id]
    UMId int [ref: > UMs.Id]
    IndustryStandarDescription varchar [note: "C925"]
    MMSID varchar [note: "57458"]
}

Table UMSAPs{
    Id int [pk, increment]
    Code varchar [note: "CCM"]
}

Table UMISOs {
    Id int [pk, increment]
    Code varchar [note: "CMQ"]
}

Table UMs {
    Id int [pk, increment]
    UMSAPId int [ref: > UMSAPs.Id]
    UMISOId int [ref: > UMISOs.Id]
}

Table UMCultures {
    UMId int [ref: > UMs.Id]
    CultureId int [ref: > Cultures.Id]
    Description varchar [note: "CM3 - Centimetro cubico"]
    Indexes {
        (UMId, CultureId)
    }
}

Table Cultures {
    Id int [pk, increment]
    Code varchar [note: "EN"]
}

Table Materials {
    Id int [pk, increment]
    Code varchar [note: "82845900"]
    StandarPrice decimal [note: "0.01"]
    PriceUnit decimal [note: "1000"]
    Currency varchar [note: "BRL"]
    MaterialGroupId int [ref: > MaterialGroups.Id]
}

Table MaterialManufacturers {
    MaterialCofidiedId int [ref: > MaterialCodifieds.Id]
    Name varchar [note: "ROCKWELL"]
    Part varchar [note: "100S-C09EJ14C"]
    Priority int [note: "1"]
    Indexes {
        (MaterialCofidiedId, Priority)
    }
}

Table MaterialCultures {
    MaterialId int [ref: > Materials.Id]
    CultureId int [ref: > Cultures.Id]
    Type int [note: "0 - SHORT y 1 - LONG"]
    Description varchar [note: "CONTATOR SEGURANCA 100S-C09EJ14C"]
    Indexes {
        (MaterialId, CultureId, Type)
    }
}

Table Contracts {
    Id int [pk, increment]
    PriceUnit decimal [note: "1000"]
    Currency varchar [note: "BRL"]
    MaterialId int [ref: > Materials.Id]
}

Table SupplierContracts {
    ContractId int [ref: > Contracts.Id]
    SupplierId int [ref: > Suppliers.Id]
    CenterId int [ref: > Centers.Id]
    Indexes {
        (ContractId, SupplierId, CenterId)
    }
}

Table Suppliers{
  Id int [pk, increment]
  MRSupplierId int [ref: > MRSuppliers.Id]
  Code varchar [note: "00100613"]
  Name varchar [note: "LADDER AUTOMAÇÃO INDUSTRIAL LTDA"]
  CountryId int [ref: > Countries.Id]
}

Table MRSuppliers {
    Id int [pk, increment]
    Code varchar [note: "100613"]
}

Table SupplierCatalogs {
    CatalogId int [ref: > Catalogs.Id]
    SupplierId int [ref: > Suppliers.Id]
    CenterId int [ref: > Centers.Id]
    Indexes {
        (CatalogId, SupplierId, CenterId)
    }
}

Table Catalogs {
    Id int [pk, increment]
    Description varchar
}

Table CatalogMaterials{
    CatalogId int
    MaterialId int
    IsCodified int
    Indexes {
        (CatalogId, MaterialId)
    }
}
ref: CatalogMaterials.CatalogId > Catalogs.Id
ref: CatalogMaterials.MaterialId > Materials.Id

Table CartMaterials {
    CartId int 
    MaterialId int
    Indexes {
        (CartId, MaterialId)
    }
}
ref: CartMaterials.CartId > Carts.Id
ref: CartMaterials.MaterialId > Materials.Id

Table Carts {
    Id int [pk, increment]
    Description varchar
}

Table PurchaseOrders{
    CartId int [ref: > Carts.Id]
    CreateDate datetime
    UserId int [ref: > Users.Id]
}

Table Users{
    Id int [pk, increment]
    FirstName varchar
    LastName varchar
    CorporationId int [ref: > Corporations.Id]
    Email varchar
    Photo varchar
    Indexes{
        (Email)
    }
}

Table UserRoles{
    UserId int [ref: > Users.Id]
    RoleId int [ref: > Roles.Id]
}

Table Roles{
    Id int [pk, increment]
    Name varchar [note: "Administrator, Contributor, Usuario Final"]
}

Table Corporations{
    Id int [pk, increment]
    Name varchar
}

Table SupplierFiles{
    Id int [pk, increment]
    SupplierId int [ref: > Suppliers.Id]
    FileName varchar [note: "file.csv"]
    Url varchar [note: "url blog storage azure"]
    Size varchar [note: "23689"]
}

Table UserMaterialFavorities{
    MaterialId int [ref: > Materials.Id]
    UserId int [ref: > Users.Id]
    Indexes {
        (UserId, MaterialId)
    }
}

Table SupplierSyncProcesses{
    Id int [pk, increment]
    SupplierId int [ref: > Suppliers.Id]
    Status varchar [note: "Running, Synchronized, Paused" ]
}

Table SupplierSyncProcessLogs{
    Id int [pk, increment]
    SupplierSyncProcessId int [ref: > SupplierSyncProcesses.Id]
    Detail varchar
    Date datetime
}

Table UserLogs{
    Id int [pk, increment]
    UserId int [ref: > Users.Id]
    Date datetime
    Detail varchar
}