Project MPC {
  database_type: 'MSSQL'
  Note: '''
    # MPC Database
    **markdown content here**
  '''
}

Table Centers {
    Id int [pk, increment]
    Code varchar [note: "X200"]
    CompanyId int [ref: > Companies.Id]
    Description varchar [note: "SEAMLESS PIPE INDONESIA JAYA"]
}

Table Companies {
    Id int [pk, increment]
    Code varchar [note: "TEFR"]
    HoldingId int [ref: > Holdings.Id]
    CountryId int [ref: > Countries.Id]
    HoldingGroupId int [ref: > HoldingGroups.Id]
}

Table Countries {
    Id int [pk, increment]
    Code varchar [note: "FR"]
}

Table Holdings {
    Id int [pk, increment]
    Code varchar [note: "SAPTEN"]
    Description varchar
}

Table HoldingGroups {
    Id int [pk, increment]
    Description varchar [note: "Tenaris"]
}

Table MaterialGroups {
    Id int [pk, increment]
    HoldingId int [ref: > Holdings.Id]
    MaterialGroupClientId int [ref: > MaterialGroupClients.Id]
    MaterialGroupExirosId int [ref: > MaterialGroupExiros.Id]
    EN_Description varchar [note: "Hardware"]
    ES_Description varchar [note: "Hardware"]
    PT_Description varchar [note: "Hardware"]
    IT_Description varchar [note: "Hardware"]
    RO_Description varchar [note: "Hardware"]
}

Table MaterialGroupClients {
    Id int [pk, increment]
    Code varchar [note: "HW"]
}

Table MaterialGroupExiros {
    Id int [pk, increment]
    Code varchar [note: "HW"]
}

Table MaterialCodifiedHoldings {
    Id int [pk, increment]
    SapMaterialId int [ref: > SapMaterials.Id]
    MaterialTypeId int [ref: > MaterialTypes.Id]
    MaterialGroupId int [ref: > MaterialGroups.Id]
    UMId int [ref: > UMs.Id]
    IndustryStandarDescription varchar [note: "C925"]
    MMSID varchar [note: "57458"]
    HoldingId int [ref: > Holdings.Id]
}

Table UMs {
    Id int [pk, increment]
    UMSAPId int [ref: > UMSAPs.Id]
    UMISOId int [ref: > UMISOs.Id]
    EN_Description varchar [note: "CM3 - Centimetro cubico"]
    ES_Description varchar [note: "CM3 - Centimetro cubico"]
    PT_Description varchar [note: "CM3 - Centimetro cubico"]
    IT_Description varchar [note: "CCM - Cubic centimter"]
    RO_Description varchar [note: "CCM - Cubic centimter"]
}

Table UMSAPs{
    Id int [pk, increment]
    Code varchar [note: "CCM"]
}

Table UMISOs {
    Id int [pk, increment]
    Code varchar [note: "CMQ"]
}

Table MaterialTypes {
    Id int [pk, increment]
    Code varchar [note: "PC"]
}

Table SapMaterials {
    Id int [pk, increment]
    Code varchar [note: "40041990"]
}

Table MaterialCodifiedCompanies {
    Id int [pk, increment]
    CompanyId int [ref: > Companies.Id]
    MaterialCodifiedHoldingId int [ref: > MaterialCodifiedHoldings.Id]
    MaterialCodifiedCenterId int [ref: > MaterialCodifiedCenters.Id]
}

Table MaterialCodifiedCenters {
    Id int [pk, increment]
    Code varchar [note: "82845900"]
    StandarPrice decimal [note: "0.01"]
    PriceUnit decimal [note: "1000"]
    Currency varchar [note: "BRL"]
    CenterId int [ref: > Centers.Id]
}

Table ContractCenters{
    Id int [pk, increment]
    MaterialCodifiedCenterId int [ref: > MaterialCodifiedCenters.Id]
    ContractId int [ref: > Contracts.Id]
}

Table Contracts {
    Id int [pk, increment]
    MaterialGroupId int [ref: > MaterialGroups.Id]
    MaterialSupplierId int [ref: > MaterialSuppliers.Id]
}

Table MaterialSuppliers{
  Id int [pk, increment]
  MRSupplierId int [ref: > MRSuppliers.Id]
  Code varchar [note: "00100613"]
  Name varchar [note: "LADDER AUTOMAÇÃO INDUSTRIAL LTDA"]
  CountryId int [ref: > Countries.Id]
}

Table MRSuppliers {
    Id int [pk, increment]
    Code varchar [note: "100613"]
}

Table MaterialNotCodifiedHoldings {
    Id int [pk, increment]
    MaterialGroupId int [ref: > MaterialGroups.Id]
    HoldingId int [ref: > Holdings.Id]
}

Table MaterialNotCodifiedCompanies {
    Id int [pk, increment]
    CompanyId int [ref: > Companies.Id]
    MaterialNotCodifiedHoldingId int [ref: > MaterialCodifiedHoldings.Id]
    MaterialCodifiedCenterId int [ref: > MaterialCodifiedCenters.Id]
}