Project MPC {
  database_type: 'MSSQL'
  Note: '''
    # MPC Database
    **markdown content here**
  '''
}

Table Countries {
    Id int [pk, increment]
    Code varchar [note: "FR"]
}

Table Holdings {
    Id int [pk, increment]
    Code varchar [note: "SAPTEN"]
    Description varchar
}

Table Companies {
    Id int [pk, increment]
    Code varchar [note: "TEFR"]
    HoldingId int [ref: > Holdings.Id]
    CountryId int [ref: > Countries.Id]
    HoldingGroupId int [ref: > HoldingGroups.Id]
}

Table Centers {
    Id int [pk, increment]
    Code varchar [note: "X200"]
    CompanyId int [ref: > Companies.Id]
    Description varchar [note: "SEAMLESS PIPE INDONESIA JAYA"]
}

Table HoldingGroups {
    Id int [pk, increment]
    HoldingId int [ref: > Holdings.Id]
    Description varchar [note: "Tenaris"]
}

Table MaterialGroupClients {
    Id int [pk, increment]
    Code varchar [note: "HW"]
}

Table MaterialGroupExiros {
    Id int [pk, increment]
    Code varchar [note: "HW"]
}

Table MaterialGroups {
    Id int [pk, increment]
    MaterialGroupClientId int [ref: > MaterialGroupClients.Id]
    MaterialGroupExirosId int [ref: > MaterialGroupExiros.Id]
    EN_Description varchar [note: "Hardware"]
    ES_Description varchar [note: "Hardware"]
    PT_Description varchar [note: "Hardware"]
    IT_Description varchar [note: "Hardware"]
    RO_Description varchar [note: "Hardware"]
}

Table MaterialTypes {
    Id int [pk, increment]
    Code varchar [note: "PC"]
}

Table SapMaterials {
    Id int [pk, increment]
    Code varchar [note: "40041990"]
}

Table MaterialCodifieds{
    Id int [pk, increment]
    CenterMaterialId int [ref: > CenterMaterials.Id]
    SapMaterialId int [ref: > SapMaterials.Id]
    MaterialTypeId int [ref: > MaterialTypes.Id]
    UMId int [ref: > UMs.Id]
    IndustryStandarDescription varchar [note: "C925"]
    MMSID varchar [note: "57458"]
}

Table UMSAPs{
    Id int [pk, increment]
    Code varchar [note: "CCM"]
}

Table UMISOs {
    Id int [pk, increment]
    Code varchar [note: "CMQ"]
}

Table UMs {
    Id int [pk, increment]
    UMSAPId int [ref: > UMSAPs.Id]
    UMISOId int [ref: > UMISOs.Id]
    EN_Description varchar [note: "CM3 - Centimetro cubico"]
    ES_Description varchar [note: "CM3 - Centimetro cubico"]
    PT_Description varchar [note: "CM3 - Centimetro cubico"]
    IT_Description varchar [note: "CCM - Cubic centimter"]
    RO_Description varchar [note: "CCM - Cubic centimter"]
}

Table CenterMaterials {
    Id int [pk, increment]
    MaterialId int [ref: > Materials.Id]
    IsCodified int
    CenterId int [ref: > Centers.Id]
}

Table Materials {
    Id int [pk, increment]
    Code varchar [note: "82845900"]
    StandarPrice decimal [note: "0.01"]
    PriceUnit decimal [note: "1000"]
    Currency varchar [note: "BRL"]
    MaterialGroupId int [ref: > MaterialGroups.Id]
}

Table Contracts {
    Id int [pk, increment]
    PriceUnit decimal [note: "1000"]
    Currency varchar [note: "BRL"]
    MaterialId int [ref: > Materials.Id]
}

Table CenterContracts{
    Id int [pk, increment]
    CenterId int [ref: > Centers.Id]
    ContractId int [ref: > Contracts.Id]
}

Table SupplierContracts {
    ContractId int [ref: > Contracts.Id]
    SupplierId int [ref: > Suppliers.Id]
    Indexes {
        (ContractId, SupplierId)
    }
}

Table Suppliers{
  Id int [pk, increment]
  MRSupplierId int [ref: > MRSuppliers.Id]
  Code varchar [note: "00100613"]
  Name varchar [note: "LADDER AUTOMAÇÃO INDUSTRIAL LTDA"]
  CountryId int [ref: > Countries.Id]
}

Table MRSuppliers {
    Id int [pk, increment]
    Code varchar [note: "100613"]
}

Table SupplierCatalogs {
    CatalogId int [ref: > Catalogs.Id]
    SupplierId int [ref: > Suppliers.Id]
    CenterId int [ref: > Centers.Id]
    Indexes {
        (CatalogId, SupplierId, CenterId)
    }
}

Table Catalogs {
    Id int [pk, increment]
    Description varchar
}

Table CatalogMaterials{
    CatalogId int
    MaterialId int
    Indexes {
        (CatalogId, MaterialId)
    }
}
ref: CatalogMaterials.CatalogId > Catalogs.Id
ref: CatalogMaterials.MaterialId > Materials.Id

Table CartMaterials {
    CartId int 
    MaterialId int
    CatalogId int  [ref: > Catalogs.Id]
    Indexes {
        (CartId, MaterialId,CatalogId)
    }
}
ref: CartMaterials.CartId > Carts.Id
ref: CartMaterials.MaterialId > Materials.Id

Table Carts {
    Id int [pk, increment]
    Description varchar
}